services:
  # 1. GATIMAN Backend API (Java Spring Boot)
  - type: web
    name: gatiman-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8088
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-da68p2vqj5pc73eu21t0-a:5432/shipit_1dix
      - key: DATABASE_USERNAME
        value: shipit_1dix_user
      - key: DATABASE_PASSWORD
        value: AzgQ14t77qRWy3xV0kyBQhTaWcXXW9qT
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: EMAIL_ENABLED
        value: "true"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USERNAME
        value: mili241105@gmail.com
      - key: EMAIL_PASSWORD
        value: hcossvokjfxvjuhi
      - key: EMAIL_FROM
        value: mili241105@gmail.com
      - key: EMAIL_FROM_NAME
        value: Ship It Logistics
      - key: RAZORPAY_KEY_ID
        value: rzp_test_TTNaA35CVbi6kG
      - key: RAZORPAY_KEY_SECRET
        value: JYOxId2dBdxzrurDVrwsy1Ws

  # 2. GATIMAN Frontend Web App (React Vite)
  - type: web
    name: gatiman-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    region: singapore
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://shipit-sl8q.onrender.com/api
      - key: VITE_WS_URL
        value: wss://shipit-sl8q.onrender.com/ws
      - key: VITE_GOOGLE_CLIENT_ID
        value: 631552883561-r8m66tevmlmtn07ice0g4oq7jidflcov.apps.googleusercontent.com
      - key: VITE_RAZORPAY_KEY_ID
        value: rzp_test_TTNaA35CVbi6kG
