spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/shipit_1dix}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password123}
    hikari:
      pool-name: ShipItPostgresPool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_TTNaA35CVbi6kG}
  key-secret: ${RAZORPAY_KEY_SECRET:JYOxId2dBdxzrurDVrwsy1Ws}
  currency: INR
  company-name: Ship It Logistics Inc.
